language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2328ccac0ae848b2a9c38f39bb77633e73cd9f01
  local_dir: dist
  on:
    branch: develop
