language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN #在 travis environment 加入 GITHUB_TOKEN
  local_dir: dist #本地路徑
  on:
    branch: develop
