language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: bd568e6577781c2344d45f863fb32f1c22052d8e
  local_dir: dist
  on:
    branch: develop
