language: node_js

node_js:
  - '4.0'

before_install:
  - export TZ=Asia/Taipei

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2c833e2098273d723cec63377ed2f75f4d16d792 # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: develop
